'use strict'

// 内置学习图谱种子：开箱即带的「前端」「Java 服务端」知识体系。
// 节点 summary = 知识点讲解（看书学的主内容），nextStep = 推荐资料与练习。

const NOW = '2026-08-01T00:00:00.000Z'

function node(id, parentId, title, status = 'unexplored', summary = '', nextStep = '') {
  return {
    id, parentId, title, status, summary, evidence: '', nextStep,
    createdAt: NOW, updatedAt: NOW,
  }
}

const BUILTIN_MAPS = [
  {
    id: 'learn_map_builtin_fe',
    title: '前端知识图谱',
    description: '内置知识体系 · 完整前端技术栈：语言核心、浏览器原理、框架、工程化、网络、性能、安全、可视化、多端、架构，多层深度，按图自学',
    builtIn: true,
    currentNodeId: 'f_hooks',
    createdAt: NOW,
    updatedAt: NOW,
    nodes: [
      node('f_root', null, '前端知识体系', 'learning',
        '前端工程师的能力树：语言与浏览器原理决定下限，框架与工程化决定生产力，性能、安全与架构决定上限。',
        '《JavaScript 高级程序设计》第 4 版 · 《Web 性能权威指南》'),

      node('f_html', 'f_root', 'HTML 与 CSS', 'unexplored',
        '结构与表现层：语义决定可维护性与可访问性，布局与动画决定表现力。',
        'MDN Web Docs · 《CSS 揭秘》'),
      node('f_semantic', 'f_html', 'HTML 语义与可访问性', 'unexplored',
        '语义化标签让文档结构对搜索引擎、屏幕阅读器和维护者都清晰；a11y 不是附加项：键盘可达、焦点可见、对比度达标是基本功。',
        '《Web 可访问性实战》· WAI-ARIA Authoring Practices'),
      node('f_layout', 'f_html', '布局体系', 'unexplored',
        '从 float/position hack 走向两大现代引擎：一维 Flex、二维 Grid。',
        'CSS-Tricks Complete Guide 系列'),
      node('f_flex', 'f_layout', 'Flexbox', 'unexplored',
        '主轴/交叉轴、grow/shrink/basis 三件套决定空间分配；justify/align 九宫格对齐；gap 取代 margin hack。',
        'CSS-Tricks《A Complete Guide to Flexbox》· Flexbox Froggy'),
      node('f_grid', 'f_layout', 'Grid', 'unexplored',
        '二维布局：轨道（fr/minmax）、区域（template-areas）、放置（线号/自动放置）；place-items + gap 组合覆盖绝大多数排版。',
        'CSS-Tricks《A Complete Guide to Grid》· Grid Garden'),
      node('f_css_adv', 'f_html', 'CSS 核心机制', 'unexplored',
        '理解规则才能从试错调样式走向推理调样式。',
        ''),
      node('f_cascade', 'f_css_adv', '层叠与优先级', 'unexplored',
        '层叠顺序：important > 优先级 > 源码顺序；优先级公式（inline > id > class > tag）；:is/:where 的优先级陷阱；!important 是最后手段。',
        'MDN《Cascade and Inheritance》'),
      node('f_bfc', 'f_css_adv', 'BFC 与视觉格式化', 'unexplored',
        '块级格式化上下文：独立渲染区域，内部浮动不影响外部；overflow:hidden/flex/absolute 触发；用于防 margin 合并与清浮动。',
        'MDN《Visual Formatting Model》'),
      node('f_anim', 'f_html', '动画与过渡', 'unexplored',
        'transition 管状态间插值，animation 管关键帧；高性能动画只用 transform/opacity（合成器线程），动 width/top 必卡顿。',
        'web.dev Animations · 《CSS 动画》'),
      node('f_responsive', 'f_html', '响应式与现代特性', 'unexplored',
        '移动优先 + 媒体查询是基线；container queries、clamp()、逻辑属性是新一代；rem/vw 适用场景要分清。',
        'web.dev Learn CSS'),

      node('f_js', 'f_root', 'JavaScript', 'unexplored',
        '前端的母语：语言机制理解深度直接决定排错能力与框架源码阅读能力。',
        '《你不知道的 JavaScript》上中卷'),
      node('f_lang', 'f_js', '语言核心', 'unexplored',
        '作用域/闭包、原型、this 三座大山。',
        '《你不知道的 JavaScript》上卷'),
      node('f_scope', 'f_lang', '作用域与闭包', 'unexplored',
        '词法作用域 + 闭包：函数记住定义时的作用域而非调用处。模块私有状态、Hooks 记忆化全部建立在闭包之上。',
        '《你不知道的 JavaScript》上卷第 1-3 章'),
      node('f_closure_app', 'f_scope', '闭包应用模式', 'unexplored',
        '防抖/节流、单例、模块模式、柯里化；React Hooks 旧值（stale closure）问题的根因与 useRef/latest-ref 对策。',
        '《JavaScript 设计模式与开发实践》'),
      node('f_proto', 'f_lang', '原型与继承', 'unexplored',
        '原型链是继承机制：实例→构造器 prototype→Object.prototype；class 是语法糖；new 的四步行为可手写实现。',
        '《你不知道的 JavaScript》中卷'),
      node('f_this', 'f_lang', 'this 与函数模式', 'unexplored',
        'this 取决于调用方式：默认/隐式/bind/new/箭头函数优先级；call/apply/bind 差异；高阶函数与柯里化。',
        '《你不知道的 JavaScript》this 与对象原型'),
      node('f_async', 'f_js', '异步与并发', 'unexplored',
        '单线程 JS 的心脏：事件循环与 Promise 状态机。',
        'Jake Archibald 事件循环演讲'),
      node('f_evloop', 'f_async', '事件循环', 'unexplored',
        '调用栈 + 宏/微任务队列：微任务（Promise/MutationObserver）在当前宏任务末清空；渲染时机与 rAF 的位置决定动画与 DOM 更新时序。',
        'MDN《Event Loop》· 《JavaScript 是怎样工作的》'),
      node('f_promise', 'f_async', 'Promise 与 async/await', 'unexplored',
        '三态不可逆；then 链与值穿透；async/await 是 generator+自动执行语法糖；并发控制 all/race/allSettled + 自定义并发数限制。',
        '《你不知道的 JavaScript》中卷异步性能'),
      node('f_ts', 'f_js', 'TypeScript', 'unexplored',
        '类型即文档、即编译期单测；大型项目生产力核心。',
        'type-challenges 题库'),
      node('f_ts_type', 'f_ts', '类型系统', 'unexplored',
        '结构化类型：泛型、联合/交叉、映射/条件类型；类型层面图灵完备，工具类型 Partial/Pick/Record/Omit 是日常武器。',
        '《TypeScript 编程》· TS 官方 Handbook'),
      node('f_ts_eng', 'f_ts', '类型收窄与工程', 'unexplored',
        '收窄手段（typeof/in/类型守卫/断言）；声明文件与第三方类型增强；strict 全开是项目底线。',
        'type-challenges · TS 官方 Handbook'),
      node('f_esmod', 'f_js', '模块系统', 'unexplored',
        'ESM 静态编译期、CJS 动态运行时；值绑定 vs 值拷贝是循环依赖行为差异的根源；import() 动态加载支撑按需分包。',
        'Node 官方《Modules》· MDN ESM'),
      node('f_mem', 'f_js', '内存管理', 'unexplored',
        '标记清除 + 分代；泄漏四来源：全局变量/遗忘定时器/闭包/Detached DOM；Chrome DevTools Memory 面板定位。',
        'MDN《Memory Management》· Addy Osmani 内存系列'),

      node('f_browser', 'f_root', '浏览器原理', 'unexplored',
        '前端的“操作系统”：渲染、事件、存储、安全。',
        '《How Browsers Work》(Tali Garsiel)'),
      node('f_render', 'f_browser', '渲染管线', 'unexplored',
        'DOM+CSSOM→Render Tree→Layout→Paint→Composite；样式重算与回是卡顿主源；分层与 will-change 是优化手段也是负担。',
        '《How Browsers Work》· web.dev Rendering'),
      node('f_reflow', 'f_render', '重排与重绘', 'unexplored',
        '重排（几何变化）代价远高于重绘；读写样式分离避免强制同步布局；transform 代替 top/left 动位置。',
        'CSSTriggers.com · MDN《Reflow》'),
      node('f_event', 'f_browser', '事件机制', 'unexplored',
        '捕获→目标→冒泡三阶段；委托利用冒泡减少监听器；stopPropagation vs preventDefault 不混用；passive 改善滚动。',
        'MDN《Event Order》· 《JavaScript 高级程序设计》事件章'),
      node('f_storage', 'f_browser', '浏览器存储', 'unexplored',
        'cookie（4KB 随请求）、localStorage（5M 同步）、sessionStorage（tab 级）、IndexedDB（异步索引大容量）；按寿命与容量选型。',
        'MDN Web Storage · IndexedDB 官方教程'),
      node('f_security', 'f_browser', '前端安全', 'unexplored',
        'XSS/CSRF 两大主力加点击劫持与依赖投毒；安全是设计约束不是补丁。',
        'OWASP Top 10 · 《Web 安全实战》'),
      node('f_xss', 'f_security', 'XSS 防御', 'unexplored',
        '本质是恶意脚本被执行：输出转义、CSP 头、HttpOnly 护 cookie；框架默认转义覆盖大部分，dangerouslySetInnerHTML/v-html 是口子。',
        'OWASP XSS Prevention Cheat Sheet'),
      node('f_csrf', 'f_security', 'CSRF 与同源策略', 'unexplored',
        '诱导已认证浏览器发请求：SameSite cookie + CSRF token + 校验 Origin 防御；同源策略是基石，CORS 是受控开口。',
        'OWASP CSRF Prevention Cheat Sheet'),

      node('f_framework', 'f_root', '框架与生态', 'unexplored',
        '框架解决状态与视图同步问题；理解原理后 API 差异只是方言。',
        ''),
      node('f_react', 'f_framework', 'React 核心', 'unexplored',
        'UI = f(state)；单向数据流 + 声明式渲染；Hooks 是状态的出入口。',
        'react.dev 官方新文档'),
      node('f_fiber', 'f_react', 'Fiber 与协调', 'unexplored',
        'diff 同类型复用实例；Fiber 把协调拆成可中断工作单元；render/commit 两阶段是并发特性的地基。',
        '《React 设计与实现》'),
      node('f_hooks', 'f_react', 'Hooks 深入', 'learning',
        'Hooks 是挂在 fiber 上的链表状态；闭包陷阱（旧值）源于不可变快照；useEffect 不是生命周期；自定义 Hook 是逻辑复用单元。',
        'react.dev · 《React 设计与实现》'),
      node('f_react_perf', 'f_react', 'React 性能优化', 'unexplored',
        'memo/useMemo/useCallback 记忆化 + 稳定引用；状态下沉；Context 拆分渲染范围；useTransition 推迟低优先级。',
        'react.dev Performance 章节'),
      node('f_virtual', 'f_react_perf', '虚拟列表与大数据渲染', 'unexplored',
        '定高索引计算、动高测量缓存；react-window/react-virtual；配合时间分片保交互流畅。',
        'react-window 文档 · TanStack Virtual'),
      node('f_vue', 'f_framework', 'Vue 核心', 'unexplored',
        '响应式依赖收集（Proxy）+ 模板编译优化（静态提升/PatchFlag）；组合式 API 与 Hooks 同构。',
        'Vue 3 官方文档《深入响应式系统》'),
      node('f_reactive', 'f_vue', '响应式原理', 'unexplored',
        'effect 读取时 track、写入时 trigger；ref vs reactive；computed/watch 的懒与调度；Proxy 对比 defineProperty 的边界。',
        '《Vue 设计与实现》'),
      node('f_state', 'f_framework', '状态管理', 'unexplored',
        '服务端状态与客户端状态分离：TanStack Query/SWR 管缓存失效重试；客户端轻量 Zustand/Context，复杂 Redux/Pinia。',
        'TanStack Query 官方课程'),
      node('f_router', 'f_framework', '路由原理', 'unexplored',
        'hash（hashchange）vs history（pushState+popstate）；路由表即 path→组件映射；守卫与懒加载；SSR 需同构路由。',
        'react-router / vue-router 官方文档'),

      node('f_eng', 'f_root', '工程化', 'unexplored',
        '把代码变成产品的流水线：构建、依赖、质量、发布。',
        '《前端架构：从传统一直到下一代》'),
      node('f_build', 'f_eng', '构建工具', 'unexplored',
        '开发体验与生产构建是两件事：dev 要快 HMR，prod 要压缩与分包。',
        'Vite 官方文档'),
      node('f_vite', 'f_build', 'Vite 原理', 'unexplored',
        'dev：原生 ESM + esbuild 预构建 + 按需编译；prod：Rollup；HMR 不随规模变慢得益于 ESM 缓存。',
        'Vite 文档「为什么选 Vite」'),
      node('f_webpack', 'f_build', 'webpack 原理', 'unexplored',
        '一切皆模块：entry→依赖图→chunk；loader 转译、plugin 挂生命周期钩子两大扩展点；存量项目主力。',
        '《webpack 实战》· 官方 concepts'),
      node('f_module', 'f_eng', '依赖管理', 'unexplored',
        'package.json 的 ^ ~ 语义与锁文件保可复现构建；依赖地狱靠 npm ls 分析与 dedup 治理。',
        'Node 官方文档 · npm 依赖治理实践'),
      node('f_quality', 'f_eng', '质量与测试', 'unexplored',
        'ESLint+Prettier 管风格；单测（Vitest）保逻辑，组件测试（Testing Library）保行为，E2E（Playwright）保关键链路。',
        'Testing Library 指导原则 · 《JavaScript 测试驱动开发》'),
      node('f_ci', 'f_eng', 'CI/CD 与发布', 'unexplored',
        '提交触发 lint→test→build→产物上传→CDN 发布；灰度 + 回滚开关；内容哈希做资源版本化。',
        '《持续交付》· GitHub Actions 文档'),
      node('f_monorepo', 'f_eng', 'Monorepo', 'unexplored',
        'pnpm workspace + Turborepo：共享依赖、增量任务编排、多包原子变更；代价是 CI 复杂度上升。',
        'Turborepo 文档 · pnpm workspace 文档'),

      node('f_net', 'f_root', '网络基础', 'unexplored',
        '前后端协作的契约层，性能优化的主战场。',
        '《HTTP 权威指南》'),
      node('f_http', 'f_net', 'HTTP 协议', 'unexplored',
        '方法语义（幂等性）、状态码精确使用、请求/响应头；理解协议才能理解缓存与安全。',
        '《HTTP 权威指南》前 6 章 · MDN HTTP'),
      node('f_cache', 'f_http', '缓存策略', 'unexplored',
        '强缓存（Cache-Control/max-age/immutable）+ 协商缓存（ETag/Last-Modified）；index.html 不缓存 + 资源长缓存内容哈希是发布标配。',
        'MDN《HTTP Caching》· Jake Archibald 缓存博客'),
      node('f_http2', 'f_http', 'HTTP/2 与 HTTP/3', 'unexplored',
        'h2 多路复用/头部压缩；h3 基于 UDP 的 QUIC 解决队头阻塞 + 0-RTT；h1 时代的资源合并优化在 h2 下已废弃。',
        '《HTTP/2 in Action》· RFC 9114/9000'),
      node('f_https', 'f_net', 'HTTPS 与 TLS', 'unexplored',
        'TLS 握手：非对称交换密钥、对称加密数据；CA 链保证身份；HSTS 强制加密。',
        '《图解 HTTP》· Cloudflare Learning TLS'),
      node('f_ws', 'f_net', 'WebSocket 与实时通信', 'unexplored',
        '全双工长连接；对比轮询/长轮询/SSE：服务端单向推 SSE 更简单；重连心跳与消息序号是工程必做。',
        'MDN WebSocket · 《WebSocket 实战》'),

      node('f_perf', 'f_root', '性能', 'unexplored',
        '体验量化为指标；优化是测量→分析→行动→回归的闭环。',
        'web.dev Performance 学习路径'),
      node('f_metrics', 'f_perf', '指标体系', 'unexplored',
        'Core Web Vitals：LCP（加载）/INP（交互）/CLS（稳定）；Performance API + RUM 采集；设预算防回归。',
        'web.dev Vitals · 《Web 性能权威指南》'),
      node('f_load', 'f_perf', '加载优化', 'unexplored',
        '减少关键资源：代码分割/路由懒加载/资源 hints（preload/prefetch）；Brotli 压缩；CDN 分发。',
        'web.dev Optimize · 《Web 性能权威指南》'),
      node('f_image', 'f_load', '图片优化', 'unexplored',
        '格式选 WebP/AVIF，响应式 srcset/sizes，懒加载 loading=lazy，CDN 裁剪参数；图片是多数页面第一流量源。',
        'web.dev 图片优化系列'),
      node('f_runtime', 'f_perf', '运行时优化', 'unexplored',
        '主线程是瓶颈：长列表虚拟、Web Worker 算、requestIdleCallback 切片、防抖节流控频。',
        '《高性能 JavaScript》· web.dev 主线程优化'),

      node('f_node', 'f_root', 'Node 与全栈', 'unexplored',
        '前端向服务端延伸：工具链、BFF、SSR 都长在这里。',
        '《Node.js 设计模式》'),
      node('f_node_core', 'f_node', 'Node 核心', 'unexplored',
        '单线程 + 事件循环 + libuv 线程池；CPU 密集阻塞全局；stream 处理大文件常数内存。',
        '《Node.js 设计模式》· 官方 Event Loop 指南'),
      node('f_ssr', 'f_node', 'SSR 与 SSG', 'unexplored',
        'SSR 首屏与 SEO 换服务器成本；SSG 预渲染静态；hydration 是桥梁；islands 架构（Astro）减少 hydration。',
        'Next.js 文档 Rendering 章节 · Astro 文档'),
      node('f_bff', 'f_node', 'BFF 与 API 协作', 'unexplored',
        'Backend For Frontend：聚合/裁剪/协议适配；OpenAPI/Mock 先行定契约；GraphQL 按需取数。',
        '《API 设计模式》· OpenAPI 官方文档'),

      node('f_visual', 'f_root', '可视化', 'unexplored',
        '数据与交互的表现层。',
        ''),
      node('f_canvas', 'f_visual', 'Canvas 与 SVG', 'unexplored',
        'Canvas 位图即时模式适合海量数据/粒子；SVG 是 DOM 矢量适合图标与可交互图表；选型看数量与交互需求。',
        'MDN Canvas 教程 · 《Canvas 实战》'),
      node('f_webgl', 'f_visual', 'WebGL 与 3D', 'unexplored',
        'GPU 可编程管线；Three.js 降低门槛（场景/相机/渲染器）；shader（GLSL）是分水岭。',
        'Three.js 官方文档 · 《WebGL 编程指南》'),
      node('f_chart', 'f_visual', '图表工程', 'unexplored',
        'ECharts 配置丰富性能好；D3 自由度最高全自建；AntV 国内生态强；从图形语法理解图表抽象。',
        'ECharts 官方示例 · 图形语法概念'),

      node('f_mobile', 'f_root', '多端开发', 'unexplored',
        '一份代码多端运行：成本与体验的永恒权衡。',
        ''),
      node('f_h5', 'f_mobile', '移动端 Web', 'unexplored',
        'viewport 与 1px 问题、触摸事件、安全区、rem/vw 适配、滚动穿透。',
        'MDN Touch Events · 移动端适配系列'),
      node('f_hybrid', 'f_mobile', 'Hybrid 与小程序', 'unexplored',
        'WebView + JSBridge 调原生能力；小程序 = 视图/逻辑双线程模型 + 自有组件生态。',
        '微信小程序官方文档 · JSBridge 原理文章'),
      node('f_cross', 'f_mobile', '跨端框架', 'unexplored',
        'Electron（Web 技术做桌面）、React Native（原生渲染）、Taro/uni-app（多端小程序）；选型看目标端与性能要求。',
        'Electron 文档 · RN 官方 Architecture'),

      node('f_arch', 'f_root', '架构与设计', 'unexplored',
        '规模化组织代码的能力。',
        ''),
      node('f_comp', 'f_arch', '组件库与设计系统', 'unexplored',
        'design tokens 统一变量；组件 API 设计（受控/非受控、slot vs props）；文档站与视觉回归是组件库门面。',
        '《Design Systems》· antd 设计文档'),
      node('f_micro', 'f_arch', '微前端', 'unexplored',
        '大团队独立交付的拆分：qiankun（沙箱/样式隔离）、Module Federation（构建级共享）、iframe 兜底；前提是领域清晰，否则是分布式单体。',
        '《微前端实战》· qiankun 文档'),
      node('f_lowcode', 'f_arch', '低代码', 'unexplored',
        '物料协议 + schema 驱动渲染 + 设计器；本质是 DSL 设计；天花板是复杂交互的表达。',
        '阿里 lowcode-engine 文档 · schema 协议文章'),
    ],
  },
  {
    id: 'learn_map_builtin_java',
    title: 'Java 服务端知识图谱',
    description: '内置知识体系 · 完整 Java 服务端技术栈：核心基础、JVM、并发、Spring 生态、存储与中间件、分布式、系统设计，四层深度，按图自学',
    builtIn: true,
    currentNodeId: 'j_ioc',
    createdAt: NOW,
    updatedAt: NOW,
    nodes: [
      node('j_root', null, 'Java 服务端知识体系', 'learning',
        '以 Java 为主线的服务端能力树：核心语法与集合是地基，JVM 与并发决定深度，Spring 生态是生产力，存储/中间件/分布式是规模化武器，系统设计是综合输出。',
        '《深入理解 Java 虚拟机》《Java 并发编程实战》《DDIA》'),

      node('j_core', 'j_root', 'Java 核心基础', 'unexplored',
        '集合、反射、泛型、IO 是框架源码阅读与日常排错的地基。',
        '《Java 核心技术 卷I》原书第 12 版'),
      node('j_oop', 'j_core', '面向对象与核心语法', 'unexplored',
        '封装/继承/多态三特性，接口与抽象类界定契约；equals/hashCode 契约、String 不可变性、final 语义是高频考点与 bug 源。',
        '《Effective Java》第 3 版 前 4 章'),
      node('j_collection', 'j_oop', '集合框架', 'unexplored',
        'Collection/Map 两大体系：ArrayList 动态数组、LinkedList 双链表、HashSet 基于 HashMap。选型看访问模式：随机读选数组，频繁插入删除选链表。',
        '《Java 核心技术 卷I》集合章节'),
      node('j_hashmap', 'j_collection', 'HashMap 原理', 'unexplored',
        '数组+链表+红黑树：hash 扰动 → 取模定位 → 链表长度≥8 且数组≥64 转红黑树；扩容 2 倍重新分布。JDK7 头插法死循环在 JDK8 尾插法解决。',
        '《Java 并发编程的艺术》第 6 章'),
      node('j_generics', 'j_collection', '泛型与类型擦除', 'unexplored',
        '泛型是编译期语法糖，运行时擦除为原始类型；PECS 原则（Producer Extends Consumer Super）决定通配符方向；不能 new T[]、不能 instanceof T。',
        '《Java 核心技术 卷I》泛型章节'),
      node('j_exception', 'j_oop', '异常体系', 'unexplored',
        'Error vs Exception；checked 强制处理、unchecked 多为编程错误。最佳实践：异常不做流程控制，try-with-resources 管资源，业务异常带错误码。',
        '《Effective Java》第 10 章'),
      node('j_io', 'j_core', 'IO 与 NIO', 'unexplored',
        'BIO 一连接一线程会阻塞；NIO 用 Channel+Buffer+Selector 单线程复用海量连接，是 Netty 与高并发服务的地基；零拷贝（sendfile）是中间件高性能的共同原理。',
        '《Netty 实战》前 3 章'),
      node('j_reflect', 'j_core', '反射与注解', 'unexplored',
        '反射是框架基石：运行时获取类信息、动态调用；注解 + 反射 + 动态代理（JDK/CGLIB）构成 Spring 的元数据驱动模型。',
        '《Java 核心技术 卷I》反射章节'),
      node('j_newfeat', 'j_core', '现代 Java 特性', 'unexplored',
        'Java 8 是分水岭：Lambda/Stream/Optional 引入函数式风格；后续 var、record、switch 表达式、虚拟线程（21）持续现代化。',
        '《Java 8 实战》· Oracle 官方 New Features 指南'),
      node('j_stream', 'j_newfeat', 'Stream API', 'unexplored',
        '惰性求值：中间操作（map/filter/flatMap）不执行，终端操作触发；并行流走 ForkJoinPool，IO 密集或有共享状态时禁用。',
        '《Java 8 实战》第 4-5 章'),

      node('j_jvm', 'j_root', 'JVM 原理与调优', 'unexplored',
        '理解 JVM 才能从“会写 Java”到“驾驭 Java”：内存、GC、类加载、排错四件套。',
        '《深入理解 Java 虚拟机》第 3 版'),
      node('j_mem', 'j_jvm', '运行时数据区', 'unexplored',
        '堆（对象实例）、虚拟机栈（栈帧：局部变量表/操作数栈）、方法区/元空间（类信息）、程序计数器。元空间用本地内存，避免永久代 OOM。',
        '《深入理解 Java 虚拟机》第 2 章'),
      node('j_gc', 'j_jvm', '垃圾回收', 'unexplored',
        '可达性分析判生死；分代假说；标记-清除/复制/整理三算法；G1 默认（Region+可预测停顿），ZGC 追求毫秒级停顿。GC 日志是调优第一手证据。',
        '《深入理解 Java 虚拟机》第 3 章 · G1 官方文档'),
      node('j_classload', 'j_jvm', '类加载机制', 'unexplored',
        '加载-验证-准备-解析-初始化；双亲委派保证一致性；SPI/热部署需要破坏委派（Thread.contextClassLoader）。',
        '《深入理解 Java 虚拟机》第 7 章'),
      node('j_jmm', 'j_jvm', 'Java 内存模型', 'unexplored',
        '主内存与工作内存的抽象；volatile 保可见性+有序性但不保原子性；happens-before 是判断可见性的唯一标准。',
        '《Java 并发编程实战》第 16 章'),
      node('j_tune', 'j_jvm', '调优与故障排查', 'unexplored',
        '流程：监控（jstat/GC 日志）→ 堆 dump（jmap + MAT/VisualVM）→ 线程问题 jstack → 在线诊断 Arthas。OOM 五类（堆/元空间/栈/直接内存/GC overhead）各有特征。',
        '《Java 性能优化权威指南》· Arthas 官方文档'),

      node('j_conc', 'j_root', '并发编程', 'unexplored',
        '并发是 Java 后端最深的护城河：线程模型、锁、容器、异步编排。',
        '《Java 并发编程实战》'),
      node('j_thread', 'j_conc', '线程基础', 'unexplored',
        '生命周期六态（NEW→RUNNABLE↔BLOCKED/WAITING/TIMED_WAITING→TERMINATED）；daemon 线程；ThreadLocal 内存泄漏根因是弱引用 key 未清理。',
        '《Java 并发编程实战》第 1 章'),
      node('j_lock', 'j_conc', '锁机制', 'unexplored',
        'synchronized 已优化（偏向/轻量/重量级锁升级）；ReentrantLock 提供可中断/公平/多条件；CAS 是无锁基石，注意 ABA 与自旋开销。',
        '《Java 并发编程的艺术》第 5 章'),
      node('j_aqs', 'j_lock', 'AQS 原理', 'unexplored',
        'state + CLH 变体队列：acquire/release 模板方法，独占/共享两种模式；ReentrantLock/CountDownLatch/Semaphore 全是它的皮肤。',
        '《Java 并发编程的艺术》第 5.6 节'),
      node('j_pool', 'j_conc', '线程池', 'unexplored',
        'ThreadPoolExecutor 七参数；任务流程：核心线程→队列→最大线程→拒绝策略。IO 密集线程数≈2N，CPU 密集≈N+1；禁用 Executors 快捷方法（无界队列 OOM）。',
        '《Java 并发编程实战》第 8 章'),
      node('j_cc', 'j_conc', '并发容器', 'unexplored',
        'ConcurrentHashMap：JDK8 = CAS+synchronized 节点粒度锁，size() 用 CounterCell 分散计数（同 LongAdder 思路）。BlockingQueue 选型：Array(有界)/Linked/Synchronous/Priority。',
        '《Java 并发编程实战》第 5 章'),
      node('j_tools', 'j_conc', '并发工具与异步编排', 'unexplored',
        'CountDownLatch 一次性、CyclicBarrier 可循环、Semaphore 限流；CompletableFuture 编排异步：thenCombine/allOf/exceptionally，注意默认 commonPool 的坑。',
        '《Java 并发编程实战》· CompletableFuture 官方 javadoc'),

      node('j_spring', 'j_root', 'Spring 生态', 'unexplored',
        '企业级 Java 的事实标准：IoC/AOP 是内核，Boot 是装配器，Cloud 是分布式套件。',
        '《Spring 实战》第 6 版'),
      node('j_ioc', 'j_spring', 'IoC 与 Bean 生命周期', 'learning',
        '控制反转 = 对象创建权交给容器；DI 三种注入（构造器优先）；Bean 生命周期：实例化→属性填充→Aware→初始化→销毁；三级缓存解决单例循环依赖。',
        '《Spring 揭秘》· 官方 Core 文档'),
      node('j_aop', 'j_spring', 'AOP 与动态代理', 'unexplored',
        '面向切面：日志/事务/权限等横切关注点；JDK 代理（接口）vs CGLIB（子类）；通知顺序与自调用失效是两大经典坑。',
        '《Spring 实战》AOP 章节'),
      node('j_mvc', 'j_spring', 'Spring MVC 请求流程', 'unexplored',
        'DispatcherServlet 总调度：HandlerMapping→适配器→参数解析/转换→Controller→消息转换；全局异常用 @RestControllerAdvice；拦截器 vs 过滤器分工。',
        '《Spring 实战》Web 章节 · 官方 MVC 文档'),
      node('j_boot', 'j_spring', 'Spring Boot 自动配置', 'unexplored',
        '@EnableAutoConfiguration + AutoConfiguration.imports + @Conditional 系列条件装配；starter = 依赖聚合 + 自动配置；约定优于配置。',
        '官方文档「Understanding Auto-configuration」· 《Spring Boot 编程思想》'),
      node('j_tx', 'j_spring', '事务管理', 'unexplored',
        '声明式事务基于 AOP；七种传播行为（REQUIRED 默认、REQUIRES_NEW 挂起外层）；失效场景：自调用、非 public、异常类型不匹配、吞异常。',
        '《Spring 揭秘》事务章节'),
      node('j_sec', 'j_spring', '安全与认证', 'unexplored',
        'Spring Security = 过滤器链；认证（AuthenticationManager）与授权（AuthorizationFilter）分离；JWT 无状态方案 + OAuth2 授权码模式对接三方登录。',
        '《Spring Security 实战》· 官方 Reference'),

      node('j_orm', 'j_root', '持久层 ORM', 'unexplored',
        'SQL 与对象模型的桥梁：MyBatis 控 SQL，JPA 控模型。',
        ''),
      node('j_mybatis', 'j_orm', 'MyBatis', 'unexplored',
        'SQL 映射框架：SqlSession→Executor→MappedStatement；#{} 预编译防注入 vs ${} 字符串拼接；一级缓存 SqlSession 级，二级缓存默认关。',
        'MyBatis 官方文档 · 《MyBatis 从入门到精通》'),
      node('j_jpa', 'j_orm', 'JPA 与 Hibernate', 'unexplored',
        'ORM 标准实现：实体三态（瞬态/持久/游离）；脏检查自动更新；懒加载与 N+1 问题（fetch join/EntityGraph 解）。',
        '《Java 持久化编程》· Hibernate 官方指南'),

      node('j_cloud', 'j_root', '微服务与 Spring Cloud', 'unexplored',
        '单体到分布式的演进套件：注册、调用、网关、容错、可观测。',
        '《微服务架构设计模式》'),
      node('j_nacos', 'j_cloud', '注册与配置中心', 'unexplored',
        '服务发现（健康检查、权重路由）+ 动态配置（长轮询推送）；Nacos AP/CP 可切换（Distro/Raft），Eureka 仅 AP。',
        'Nacos 官方文档 · 《Spring Cloud Alibaba 实战》'),
      node('j_feign', 'j_cloud', '远程调用与负载均衡', 'unexplored',
        '声明式 HTTP 客户端：接口+注解生成调用；客户端负载均衡（LoadBalancer）；超时/重试/降级要显式配置，默认值都是坑。',
        'Spring Cloud 官方 OpenFeign 章节'),
      node('j_gateway', 'j_cloud', '服务网关', 'unexplored',
        '统一入口：路由+过滤器链（鉴权/限流/灰度）；Spring Cloud Gateway 基于 WebFlux 非阻塞；与 Nginx 分工（七层业务 vs 四层/静态）。',
        '官方 Gateway 文档'),
      node('j_sentinel', 'j_cloud', '熔断与限流', 'unexplored',
        '限流算法（令牌桶/滑动窗口）；熔断三态（开/半开/闭）；Sentinel 以资源为粒度、规则动态推送；舱壁隔离防雪崩。',
        'Sentinel 官方文档 · 《SRE》熔断章节'),
      node('j_trace', 'j_cloud', '分布式链路追踪', 'unexplored',
        'TraceId/SpanId 贯穿调用链；SkyWalking 无侵入探针 vs OpenTelemetry 标准；日志带 traceId 是排错刚需。',
        'SkyWalking 官方文档 · 《分布式系统可观测性》'),

      node('j_db', 'j_root', '数据库与缓存', 'unexplored',
        '存储层选型与调优是后端日常工作的重心。',
        '《DDIA》'),
      node('j_mysql', 'j_db', 'MySQL 内核', 'unexplored',
        '围绕 InnoDB 四大件：索引结构、事务、锁、日志（redo/undo/binlog）。',
        '《高性能 MySQL》第 4 版'),
      node('j_index', 'j_mysql', '索引与 B+ 树', 'unexplored',
        'B+ 树叶子节点链表支撑范围查询；聚簇索引 vs 二级索引（回表）；最左前缀、覆盖索引、索引下推；失效场景：函数/隐式转换/like% 前缀。',
        '《MySQL 技术内幕：InnoDB 存储引擎》第 5 章'),
      node('j_txn', 'j_mysql', '事务与锁', 'unexplored',
        'ACID 靠 redo（持久）+ undo（原子）+ 锁/MVCC（隔离）；四隔离级别，RR 下 MVCC+next-key lock 防大部分幻读；死锁排查看 SHOW ENGINE INNODB STATUS。',
        '《MySQL 技术内幕》事务章节 · 官方 InnoDB 文档'),
      node('j_sql', 'j_mysql', 'SQL 优化', 'unexplored',
        'EXPLAIN 看 type/key/rows/Extra；优化顺序：索引设计 > 语句改写 > 深分页（延迟关联）> 表结构（范式设计反范式读）。',
        '《高性能 MySQL》第 6 章'),
      node('j_shard', 'j_mysql', '分库分表', 'unexplored',
        '垂直拆分按业务，水平拆分按数据量；分片键选择决定查询模式；分布式 ID（雪花算法）；中间件 ShardingSphere；扩容用双倍预分片。',
        '《DDIA》第 6 章 · ShardingSphere 文档'),
      node('j_redis', 'j_db', 'Redis', 'unexplored',
        '内存 KV 的多面手：缓存、分布式锁、计数器、排行榜、消息流。',
        '《Redis 设计与实现》'),
      node('j_redis_ds', 'j_redis', '数据结构与场景', 'unexplored',
        'String（缓存/计数）、Hash（对象）、List（队列）、Set（去重/交集）、ZSet（排行榜/延迟队列）；底层编码优化（ziplist/intset）是内存友好的关键。',
        '《Redis 设计与实现》第一部分'),
      node('j_redis_persist', 'j_redis', '持久化与高可用', 'unexplored',
        'RDB 快照 vs AOF 追加（混合持久化）；主从复制（全量+增量）；哨兵自动故障转移；Cluster 16381 槽分片。',
        '《Redis 设计与实现》第二、三部分 · 官方 Cluster 教程'),
      node('j_redis_cache', 'j_redis', '缓存三大问题', 'unexplored',
        '穿透（查不存在→布隆/空值缓存）、击穿（热点过期→互斥/逻辑过期）、雪崩（集体过期→随机 TTL/多级缓存）；一致性：先更新 DB 再删缓存 + 延迟双删/订阅 binlog。',
        '《Redis 核心原理与实战》· 美团缓存系列文章'),
      node('j_redis_lock', 'j_redis', '分布式锁', 'unexplored',
        'SETNX+过期 的缺陷（误删/续期）；Redisson 看门狗自动续期 + 可重入；Redlock 的时钟争议（Martin vs Antirez）；强一致场景用 ZooKeeper 临时节点。',
        'Redisson 官方文档 · Martin Kleppmann 对 Redlock 的分析'),

      node('j_mq', 'j_root', '消息队列', 'unexplored',
        '异步解耦削峰的核心中间件。',
        ''),
      node('j_mq_core', 'j_mq', 'MQ 核心价值与通病', 'unexplored',
        '解耦/异步/削峰三价值；四必答题：丢失（生产/存储/消费三端确认）、重复（消费端幂等）、顺序（分区有序）、积压（扩容/降级）。',
        '《DDIA》第 11 章'),
      node('j_kafka', 'j_mq', 'Kafka', 'unexplored',
        '分区+顺序追加=高吞吐；consumer group rebalance；acks 配置权衡（all+min.insync）；offset 提交时机决定 at-least-once。',
        '《Kafka 权威指南》'),
      node('j_rocketmq', 'j_mq', 'RocketMQ', 'unexplored',
        '事务消息（half+回查）、顺序消息（队列选择）、延迟级别；NameServer 无状态注册中心。',
        'RocketMQ 官方开发者文档'),

      node('j_dist', 'j_root', '分布式理论', 'unexplored',
        '分布式的边界与武器库：CAP、事务、幂等、共识。',
        ''),
      node('j_cap', 'j_dist', 'CAP 与 BASE', 'unexplored',
        '分区必现，P 成立时 C/A 二选一；工程上多为 AP+最终一致（BASE）；CP 场景：锁/配置中心。',
        '《DDIA》第 9 章 · CAP 原始论文'),
      node('j_dist_txn', 'j_dist', '分布式事务', 'unexplored',
        '2PC 同步阻塞单点；TCC 业务侵入换性能；Saga 长事务补偿；本地消息表/事务消息最终一致；Seata AT 低侵入。选型：先最终一致，后强一致。',
        '《凤凰架构》分布式事务章节 · Seata 官方文档'),
      node('j_idem', 'j_dist', '幂等设计', 'unexplored',
        '重试的前提是幂等：唯一索引/防重表、token 机制、状态机前置校验、乐观锁版本号。',
        '《DDIA》第 12 章'),
      node('j_consensus', 'j_dist', '共识算法', 'unexplored',
        'Raft：领导选举+日志复制，工程友好（etcd/consul）；Paxos 理论完备难实现；理解 term/多数派即可读懂多数中间件。',
        'Raft 论文 · thesecretlivesofdata.com/raft 交互动画'),

      node('j_base', 'j_root', '计算机基础', 'unexplored',
        '网络/操作系统/算法是理解一切中间件原理的底座。',
        ''),
      node('j_net', 'j_base', '计算机网络', 'unexplored',
        'TCP 三次握手防历史连接、四次挥手 TIME_WAIT；滑动窗口/拥塞控制；HTTPS = TLS（对称+非对称+CA）；HTTP/2 多路复用、HTTP/3 QUIC。',
        '《计算机网络：自顶向下方法》第 3、6 章'),
      node('j_os', 'j_base', '操作系统', 'unexplored',
        '进程/线程/协程成本对比；用户态/内核态与系统调用；IO 模型（阻塞/非阻塞/IO 多路复用/零拷贝）是中间件高性能的共同原理。',
        '《操作系统导论》(OSTEP) · 《UNIX 网络编程》卷 1'),
      node('j_algo', 'j_base', '数据结构与算法', 'unexplored',
        '复杂度分析是通用语言；高频模式：哈希、双指针、滑动窗口、BFS/DFS、DP 入门；刷题重模式识别而非背题。',
        '《算法》第 4 版 · LeetCode Hot 100'),

      node('j_eng', 'j_root', '工程化与运维', 'unexplored',
        '把代码安全、持续地送上生产。',
        ''),
      node('j_maven', 'j_eng', '构建与依赖管理', 'unexplored',
        'Maven 生命周期/仓库/依赖调解（路径最近优先）；Gradle 增量构建更快；dependency:tree 解冲突；统一版本用 BOM/dependencyManagement。',
        'Maven 官方 Guide · 《Maven 实战》'),
      node('j_test', 'j_eng', '测试体系', 'unexplored',
        'JUnit5（参数化/扩展）+ Mockito（mock/stub 边界）；测试金字塔：单测多、集成中、E2E 少；Testcontainers 做真实依赖集成测试。',
        '《单元测试的艺术》· Testcontainers 官方文档'),
      node('j_docker', 'j_eng', '容器与 K8s', 'unexplored',
        '镜像分层/联合文件系统；Dockerfile 最佳实践（小基础镜像/多阶段构建）；K8s 核心：Pod/Deployment/Service/Ingress + 健康探针。',
        '《Docker 实战》· K8s 官方 Interactive Tutorials'),
      node('j_cicd', 'j_eng', 'CI/CD', 'unexplored',
        '流水线即代码：提交→构建→测试→镜像→部署；蓝绿/金丝雀发布；GitOps（ArgoCD）让部署声明化。',
        '《持续交付》· GitLab CI 官方文档'),
      node('j_obs', 'j_eng', '可观测性', 'unexplored',
        '三支柱：Metrics（Prometheus+Grafana）、Logs（ELK/Loki 结构化）、Traces（SkyWalking/OTel）；RED/USE 方法定监控指标；告警要分级。',
        '《SRE》监控章节 · Prometheus 官方文档'),
      node('j_nginx', 'j_eng', 'Nginx', 'unexplored',
        '事件驱动异步架构；反向代理/负载均衡（轮询/权重/ip_hash）；动静分离与缓存；location 匹配优先级是 conf 核心。',
        'Nginx 官方文档 · 《深入 Nginx》'),

      node('j_design', 'j_root', '系统设计', 'unexplored',
        '把前面所有知识串成方案的综合输出层。',
        ''),
      node('j_high_conc', 'j_design', '高并发设计', 'unexplored',
        '三板斧：缓存（多级）、异步（MQ）、水平扩展（无状态）；读写分离；热点探测与本地缓存；全链路压测定容量。',
        '《大型网站技术架构》· 《DDIA》'),
      node('j_ha', 'j_design', '高可用与容灾', 'unexplored',
        '限流（令牌桶）、熔断、降级、超时与重试（指数退避+抖动）；多活与容灾切换；SLA 99.9→99.99 是数量级的投入差。',
        '《SRE》· 《发布！软件系统的设计与组织》'),
      node('j_case', 'j_design', '经典场景设计', 'unexplored',
        '秒杀（库存预扣+MQ 削峰+限流）、短链（发号+base62）、Feed 流（推拉结合）、订单超时（延迟队列）、排行榜（ZSet）。用场景串联全部知识。',
        '《后端技术实战课》· 大厂技术博客架构案例'),
    ],
  },
]

// 被新版替代的旧内置图谱，启动时移除（仅限内置 id，不碰用户自建）
const DEPRECATED_BUILTIN_IDS = ['learn_map_builtin_backend', 'learn_map_builtin_frontend']

module.exports = { BUILTIN_MAPS, DEPRECATED_BUILTIN_IDS }
